<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>range</name>
   <tag></tag>
   <elementGuidId>5f87c2f6-35ef-49a3-9dde-aaa653c88745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;c3-subPanel-_x-price-textrange&quot;]/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;c3-subPanel-_x-price-textrange&quot;]/div/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
